logging_config:
  log_file: './log'

db_config:
  database: 'database'
  user: 'user'
  password: 'password'
  
slicer_config:
  slicer_path: '/foo/slicer'
  tape_location: "/foo/input/tape_id"
  output_directory: "/foo/output/tape_id/slicer"
  log_file: "/foo/output/tape_id/slicer/slicer.log"

linker_config:
  output_directory: "/foo/output/tape_id/linker"
  agid_name_lookup_table: "table_name"
  file_patterns: ['[A-Z0-9]*.[A-Z0-9]*.[A-Z0-9]*', '[A-Z0-9]*.[A-Z0-9]*']

uploader_config:
  verify_ssl: false
  s3_bucket: 'sample-bucket'
  s3_prefix: 'sample/prefix'