db_config:
  database: 'database'
  user: 'user'
  password: 'password'

linker_config:
  source_dir: "/foo/output/tape_id/slicer"
  target_base_dir: "/foo/output/tape_id/linker"
  agid_name_lookup_table: "table_name"
  file_pattern: '\w+\.\w+\.\w+|\w+\.\w+'