tape_register_table: 'db_tape_register_table'
output_working_directory: '/foo/output/'

db_config:
  database: 'database'
  user: 'user'
  password: 'password'
  
tape_import_confirmer_config:
  tape_directory: '/foo/tapes'
  ready_extension: '.exported'
  timeout: 60
  check_interval: 1
  
slicer_config:
  slicer_path: '/foo/slicer'

sanity_checker_config:
  sanity_checker_path: '/foo/slicer'

linker_config:
  agid_name_lookup_table: "table_name"
  file_patterns: ['[A-Z0-9]*.[A-Z0-9]*.[A-Z0-9]*', '[A-Z0-9]*.[A-Z0-9]*']

uploader_config:
  verify_ssl: false
  s3_bucket: 'sample-bucket'
  s3_prefix: 'sample/prefix'